### PR TITLE
Add Translation PDF support to API

### PR DESCRIPTION
**Pull request by blitzwolfz**
Wrote the backend code needed for the translation pdf file upload, download, and stream to front end. There are example files in plain html on how to upload and delete but will modify the front end to support both upload and delete soon. Can test the API using Postman.

- [x] Add initial files
- [x] Add API Handling of upload
- [x] Add API Handling of delete
- [x] Add API Handling of stream
- [x] Add API Handling of view all
- [x] Add API Routes
- [x] Test API in POSTMAN
- [x] Write initial Front End

Will merge when complete or review and merge when complete

### CODE REVIEW

**Comment by blitzwolfz** [comment]
Good to merge if you wish. Can test it by downloading my repo and testing that, just remember to switch the env key

**Comment by blitzwolfz** [comment]
Final commit needed

**Comment by blitzwolfz** [comment]
Final Final commit

**Review by Can1Cyp2 — APPROVED** [review]
Very nice!

**Pull request merged**
